CREATE SEQUENCE TDS_MVC_SEQ_MERCADO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TDS_MVC_TB_MERCADO (
    ID NUMBER(19, 0) NOT NULL,
    NOME VARCHAR2(120) NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    SETOR VARCHAR2(80) NOT NULL,
    TAMANHO VARCHAR2(40) NOT NULL,
    PRECO NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_TDS_MVC_TB_MERCADO PRIMARY KEY (ID)
);
